name: Python

on: workflow_dispatch

jobs:
  job1:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: ["3.8"]
      steps:
        - uses: actions/checkout@v3
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}
        - name: Archive Python version
          run: |
            mkdir -p path/artifacts
            python -c "import sys; print(sys.version)" > path/artifacts/version-3.8.txt
        - name: Upload Artifact
          uses: actions/upload-artifact@v3
          with:
            name: my-artifact
            path: path/artifacts/version-3.8.txt
            
  job2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Archive Python version
        run: |
          python -c "import sys; print(sys.version)" > path/artifacts/version-3.9.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: path/artifacts/version-3.9.txt
        
  job3:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
          - uses: actions/checkout@v3
          - name: Set up Python ${{ matrix.python-version }}
            uses: actions/setup-python@v4
            with:
              python-version: ${{ matrix.python-version }}
          - name: Archive Python version
            run: |
              python -c "import sys; print(sys.version)" > path/artifacts/version-3.10.txt
          - name: Upload Artifact
            uses: actions/upload-artifact@v3
            with:
              name: my-artifact
              path: path/artifacts/version-3.10.txt
